### ISSUE TITLE
word2vec训练的结果不准确

### ISSUE THREAD

**Issue by datawlb** [Angel-ML/angel#1008]
不知道大家有没有碰到结果准确性的问题，
当前用deepwalk对graph进行采样生成长度为9的序列，图有2.8w的节点，每个节点采样100次，就是280w个序列，然后用angel word2vec训练
1.参数：嵌入维度32，用skip-gram, 学习率0.01，迭代次数3，batchsize 128, negative 5, window 3
angel版本2.2.0
2.序列出的结果：联系较紧密的节点，和无联系的节点，其余弦相似性很随机，未表现出联系紧密的相似性高，无联系的相似度低等行为。
3. 然后用同样的采样序列数据280w，用gensim训练，相同参数，很好的表现出了联系紧密的相似性高(0.9)，无联系的相似度低(<0.5)等行为（用同样的数据测试）

**Comment by Leputa** [comment]
这个的实现负采样有问题

**Comment by datawlb** [comment]
> 这个的实现负采样有问题

谢谢提醒！我看到他的实现确实和gensim框架不一样，随机生成的负样本也有可能是在词的窗口里，想问下您这边后面有做一些更改吗？

**Comment by Leputa** [comment]
没有, 我不会scala，只是发现效果不好后看了看代码

**Comment by FreyYann** [comment]
![image](https://user-images.githubusercontent.com/28909028/93959198-bf003f00-fd8a-11ea-9b1a-c4608935c941.png)
这两行代码换一下

**Comment by ouyangwen-it** [comment]
> 不知道大家有没有碰到结果准确性的问题，
> 当前用deepwalk对graph进行采样生成长度为9的序列，图有2.8w的节点，每个节点采样100次，就是280w个序列，然后用angel word2vec训练
> 1.参数：嵌入维度32，用skip-gram, 学习率0.01，迭代次数3，batchsize 128, negative 5, window 3
> angel版本2.2.0
> 2.序列出的结果：联系较紧密的节点，和无联系的节点，其余弦相似性很随机，未表现出联系紧密的相似性高，无联系的相似度低等行为。
> 3. 然后用同样的采样序列数据280w，用gensim训练，相同参数，很好的表现出了联系紧密的相似性高(0.9)，无联系的相似度低(<0.5)等行为（用同样的数据测试）

你好，请问你有用最新的3.1.0版本的跑过吗

**Comment by datawlb** [comment]
> ![image](https://user-images.githubusercontent.com/28909028/93959198-bf003f00-fd8a-11ea-9b1a-c4608935c941.png)
> 这两行代码换一下

谢谢您的回复！

**Comment by datawlb** [comment]
> > 不知道大家有没有碰到结果准确性的问题，
> > 当前用deepwalk对graph进行采样生成长度为9的序列，图有2.8w的节点，每个节点采样100次，就是280w个序列，然后用angel word2vec训练
> > 1.参数：嵌入维度32，用skip-gram, 学习率0.01，迭代次数3，batchsize 128, negative 5, window 3
> > angel版本2.2.0
> > 2.序列出的结果：联系较紧密的节点，和无联系的节点，其余弦相似性很随机，未表现出联系紧密的相似性高，无联系的相似度低等行为。
> > 3. 然后用同样的采样序列数据280w，用gensim训练，相同参数，很好的表现出了联系紧密的相似性高(0.9)，无联系的相似度低(<0.5)等行为（用同样的数据测试）
> 
> 你好，请问你有用最新的3.1.0版本的跑过吗

谢谢跟进，不好意思，最近没跟这个事情了，不过好像用deepwalk跑的嵌入效果比较正常，貌似skip-gram是调用Wordvec库的(3.1版本的)
