### ISSUE TITLE
When is PSMatrixInit function being called？

### ISSUE THREAD

**Issue by linjiuning** [Angel-ML/angel#1016]
I just ran the example of wordvec, but get com.tencent.angel.ps.server.data.request.GetUDFRequest@c failed java.lang.NullPointerException.

I must call model.randomInitialize before train to avoid the exception.

Seems like mc.setInitFunc(new LINEInitFunc(2, embeddingDim)) doesn't work?

**Comment by linjiuning** [comment]
I just ran the example of wordvec, but get `com.tencent.angel.ps.server.data.request.GetUDFRequest@c failed java.lang.NullPointerException`. 

I must call model.randomInitialize before train to avoid the exception.

Seems like `mc.setInitFunc(new LINEInitFunc(2, embeddingDim))` doesn't work?

**Comment by ouyangwen-it** [comment]
you should explicit call initialize before train.

**Comment by linjiuning** [comment]
So what‘s initFunc is used for？

**Comment by ouyangwen-it** [comment]
> So what‘s initFunc is used for？

This initFunc now is not be used anymore, we will remove it.
