### ISSUE TITLE
Word2Vec SERVER_IS_BUSY

### ISSUE THREAD

**Issue by linjiuning** [Angel-ML/angel#1024]
训练词向量时报错

20/10/09 10:37:54 ERROR MatrixTransportClient: request GetUDFRequest{getFuncClass='com.tencent.angel.graph.embedding.line.LINEGetEmbedding', partParam=PartitionGetParam{matrixId=1, partKey=PartitionKey(matrixId=1, partitionId=0, startRow=0, startCol=0, endRow=1, endCol=7978534)indexNum=-1)}} PartitionRequest{clock=0, partKey=PartitionKey(matrixId=1, partitionId=0, startRow=0, startCol=0, endRow=1, endCol=7978534)indexNum=-1), comeFromPs=false} com.tencent.angel.ps.server.data.request.GetUDFRequest@3 has a exception response GetUDFResponse [partResult=null, toString()=Response{state=BUSY, responseType=SERVER_IS_BUSY, detail='server is busy now, retry later'}]
20/10/09 10:37:58 WARN MatrixTransportClient: PS ParameterServer_0 is in gray server list, Send hb to it to check

**Comment by linjiuning** [comment]
ps端log报错
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 110614597 byte(s) of direct memory (used: 2224825794, max: 2335178752)

**Comment by ouyangwen-it** [comment]
跑的angel哪个版本，batchsize设的多大，麻烦把运行参数贴下看看
