### ISSUE TITLE
/dist/target目录下面没有pyangel

### ISSUE THREAD

**Issue by gxlzlihao** [Angel-ML/angel#1030]
本人将pom.xml之中所依赖的protobuf版本由2.5.0修改为3.11.4之后，在成功编译项目源码之后在目录/dist/target下面没有找到pyangel执行程序？

**Comment by ouyangwen-it** [comment]
pyangel迁移到pytorch on angel项目了，可查看https://github.com/Angel-ML/PyTorch-On-Angel/tree/master
