### ISSUE TITLE
Louvain算法跑出结果与预期不一致

### ISSUE THREAD

**Issue by dongxuej** [Angel-ML/angel#1031]
**description：**我发现所有节点最后都会归为一个社区。
为了验证这件事情出现的必然性，我目前已经造了一个最简单的原始数据，一共2条边的数据，1，2一条边、3，4一条边，然后分社区的时候，1、2、3、4点都归为了1个社区id，id为1

**Comment by dongxuej** [comment]
**description：**我发现所有节点最后都会归为一个社区。
为了验证这件事情出现的必然性，我目前已经造了一个最简单的原始数据，一共2条边的数据，1，2一条边、3，4一条边，然后分社区的时候，1、2、3、4点都归为了1个社区id，id为1

**Comment by ouyangwen-it** [comment]
使用branch-3.1.0最新版本的louvain算法跑下看看

**Comment by dongxuej** [comment]
OK了，最新版本很给力，感谢哦！
