### ISSUE TITLE
请教关于graph中Closeness算法精度设置问题

### ISSUE THREAD

**Issue by datian9966** [Angel-ML/angel#1033]
麻烦能具体解释一下p和sp参数吗？
目前在非常小的数据量(就手工造的十几条边)下进行测试时，结果不准确，且不稳定
根据不同的数据集大小或疏密的情况下，这两个参数应该如何设置呢？感谢！

**Comment by xs-li** [comment]
closeness当前是针对一个连通分量；通常建议sp设置为0，p默认为6

**Comment by xs-li** [comment]
closeness当前是针对一个连通分量；
p和sp是HyperLogLogPlus类的参数，p值通常用于正常数据集，sp用来调节稀疏数据集,sp越大错误率越低，但是内存开销也越大；p值越大精度越高，计算也更耗时；默认建议sp设置为0，p默认为6
可以参考：[Choosing p,sp介绍](https://metron.apache.org/current-book/metron-analytics/metron-statistics/HLLP.html )

**Comment by datian9966** [comment]
@xs-li 谢谢您！明白了~
