### ISSUE TITLE
LPA useBalancePartition 参数函数缺失

### ISSUE THREAD

**Issue by dongxuej** [Angel-ML/angel#1036]
LPA算法，指定参数useBalancePartition ：true时，报方法缺失错误。
![image](https://user-images.githubusercontent.com/24312864/97973563-3d77e400-1e01-11eb-8a00-41a6a6b905d8.png)

**Comment by xs-li** [comment]
I set useBalancePartition=true，the error didn't appear. have you solved this problem？
