### ISSUE TITLE
LPA迭代疑问

### ISSUE THREAD

**Issue by dongxuej** [Angel-ML/angel#1037]
测试数据有3条边：
1，2
3，4
1，5
期望输出：
1，1
5，1
2，2
3，3
4，4
实际跑算法的时候我发现从迭代2次开始，就能出现上述的期望输出了，但是假如我设置迭代次数为20次，那么从第2次开始一直到20次，结果是一致的，都是上述期望输出的内容。
我现在有一些疑问，就是既然lpa label已经从第3次开始不发生改变了，为什么迭代还没有自行终止，而且log日志里，还显示有5个lpa label发生改变，而不是0个。

**Comment by Gscim** [comment]
你好，标签传播算法判断每个点邻居里面数量最多的标签，然后赋值给自己。算法的终止条件是数据不再更新。您给的样例数据集里比如3-4组成的图，每轮判断的时候都发现邻居的标签跟自己不同，会进行修改。这样产生震荡。包括1，2；1，5的图也会产生震荡。

**Comment by dongxuej** [comment]
> 你好，标签传播算法判断每个点邻居里面数量最多的标签，然后赋值给自己。算法的终止条件是数据不再更新。您给的样例数据集里比如3-4组成的图，每轮判断的时候都发现邻居的标签跟自己不同，会进行修改。这样产生震荡。包括1，2；1，5的图也会产生震荡。

那你是说这个和数据集是强相关的~我拿几百万条边的业务数据去跑的时候，也会出现一模一样的问题，lpa label update的数量一直都是最大值，没有减小！如果用几亿的数据集就会好很多，这个lpa label更新的数量会不断减小，但是收敛极慢，200次迭代，平均每轮只会少更新一万，简单粗略算一下，那可能也至少需要迭代几千次；咱们ps服务器是不是纯内存的呀？我发现迭代次数很多的时候，就崩了。

**Comment by xs-li** [comment]
> 测试数据有3条边：
> 1，2
> 3，4
> 1，5
> 期望输出：
> 1，1
> 5，1
> 2，2
> 3，3
> 4，4
> 实际跑算法的时候我发现从迭代2次开始，就能出现上述的期望输出了，但是假如我设置迭代次数为20次，那么从第2次开始一直到20次，结果是一致的，都是上述期望输出的内容。
> 我现在有一些疑问，就是既然lpa label已经从第3次开始不发生改变了，为什么迭代还没有自行终止，而且log日志里，还显示有5个lpa label发生改变，而不是0个。

ensure undirected graph： a->b and b->a

**Comment by dongxuej** [comment]
> > 测试数据有3条边：
> > 1，2
> > 3，4
> > 1，5
> > 期望输出：
> > 1，1
> > 5，1
> > 2，2
> > 3，3
> > 4，4
> > 实际跑算法的时候我发现从迭代2次开始，就能出现上述的期望输出了，但是假如我设置迭代次数为20次，那么从第2次开始一直到20次，结果是一致的，都是上述期望输出的内容。
> > 我现在有一些疑问，就是既然lpa label已经从第3次开始不发生改变了，为什么迭代还没有自行终止，而且log日志里，还显示有5个lpa label发生改变，而不是0个。
> 
> ensure undirected graph： a->b and b->a
> 1,2
> 2,1
> 3,4
> 4,3
> 1,5
> 5,1

这个不是会自动补全的吗？

**Comment by xs-li** [comment]
> 测试数据有3条边：
> 1，2
> 3，4
> 1，5
> 期望输出：
> 1，1
> 5，1
> 2，2
> 3，3
> 4，4
> 实际跑算法的时候我发现从迭代2次开始，就能出现上述的期望输出了，但是假如我设置迭代次数为20次，那么从第2次开始一直到20次，结果是一致的，都是上述期望输出的内容。
> 我现在有一些疑问，就是既然lpa label已经从第3次开始不发生改变了，为什么迭代还没有自行终止，而且log日志里，还显示有5个lpa label发生改变，而不是0个。

蒲公英结构在lpa迭代中是奇偶次迭代交互社区id的，参考spark graphx ：https://github.com/apache/spark/blob/branch-2.4/graphx/src/main/scala/org/apache/spark/graphx/lib/LabelPropagation.scala
蒲公英结构，如：
1,2
1,3
1,4

**Comment by dongxuej** [comment]
> > 测试数据有3条边：
> > 1，2
> > 3，4
> > 1，5
> > 期望输出：
> > 1，1
> > 5，1
> > 2，2
> > 3，3
> > 4，4
> > 实际跑算法的时候我发现从迭代2次开始，就能出现上述的期望输出了，但是假如我设置迭代次数为20次，那么从第2次开始一直到20次，结果是一致的，都是上述期望输出的内容。
> > 我现在有一些疑问，就是既然lpa label已经从第3次开始不发生改变了，为什么迭代还没有自行终止，而且log日志里，还显示有5个lpa label发生改变，而不是0个。
> 
> 蒲公英结构在lpa迭代中是奇偶次迭代交互社区id的，参考spark graphx ：https://github.com/apache/spark/blob/branch-2.4/graphx/src/main/scala/org/apache/spark/graphx/lib/LabelPropagation.scala
> 蒲公英结构，如：
> 1,2
> 1,3
能给个讲蒲公英结构的文章或者链接我学习一下吗？我看看我们的业务源数据是不是蒲公英结构？

**Comment by dongxuej** [comment]
> > 测试数据有3条边：
> > 1，2
> > 3，4
> > 1，5
> > 期望输出：
> > 1，1
> > 5，1
> > 2，2
> > 3，3
> > 4，4
> > 实际跑算法的时候我发现从迭代2次开始，就能出现上述的期望输出了，但是假如我设置迭代次数为20次，那么从第2次开始一直到20次，结果是一致的，都是上述期望输出的内容。
> > 我现在有一些疑问，就是既然lpa label已经从第3次开始不发生改变了，为什么迭代还没有自行终止，而且log日志里，还显示有5个lpa label发生改变，而不是0个。
> 
> 蒲公英结构在lpa迭代中是奇偶次迭代交互社区id的，参考spark graphx ：https://github.com/apache/spark/blob/branch-2.4/graphx/src/main/scala/org/apache/spark/graphx/lib/LabelPropagation.scala
> 蒲公英结构，如：
> 1,2
> 1,3
> 1,4

能给个讲蒲公英结构的文章或者链接我学习一下吗？我看看我们的业务源数据是不是蒲公英结构？

**Comment by xs-li** [comment]
蒲公英社区只是形象的比喻，类似发散松散的社区结构：推荐篇综述性质的文章，https://arxiv.org/pdf/0906.0612.pdf；另外http://snap.stanford.edu/papers.html 也有不少好的文章讲社区发现；后面我会规整到angel的子项目，papers-we-learn，也欢迎关注
