### ISSUE TITLE
计算closeness陷入一直running的状态

### ISSUE THREAD

**Issue by Post-Dawn** [Angel-ML/angel#1038]
计算closeness状态一直处于running
input： 
1 2
2 3
运行bash为：
input=hdfs:///data/dx.edges
output=hdfs:///output

source ./spark-on-angel-env.sh
$SPARK_HOME/bin/spark-submit \
  --master yarn-cluster\
  --conf spark.ps.instances=1 \
  --conf spark.ps.cores=4 \
  --conf spark.ps.jars=$SONA_ANGEL_JARS \
  --conf spark.ps.memory=10g \
  --name "commonfriends angel" \
  --jars $SONA_SPARK_JARS  \
  --driver-memory 5g \
  --num-executors 1 \
  --executor-cores 8 \
  --executor-memory 8g \
  --queue default \
  --class com.tencent.angel.spark.examples.cluster.ClosenessExample \
  $ANGEL_HOME/lib/spark-on-angel-examples-3.1.0.jar \
  input:$input output:$output sep:space storageLevel:MEMORY_ONLY useBalancePartition:true \
  balancePartitionPercent:0.7 partitionNum:4 psPartitionNum:1 msgNumBatch:8 \
  pullBatchSize:1000 verboseSaving:true src:1 dst:2 mode:yarn-cluster
spark日志为：
![image](https://user-images.githubusercontent.com/26621292/98543798-f3de3c00-22cd-11eb-9425-16f98187e8de.png)

**Comment by xs-li** [comment]
the dataset is so small，you can set ”partitionNum=1“，don't let the data partition be empty ；
