### ISSUE TITLE
build failure on A64FX, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [Angel-ML/angel#1039]
... 
[INFO] angel-ps ........................................... SUCCESS [ 10.623 s]
[INFO] angel-ps-core ...................................... FAILURE [  1.120 s]
[INFO] angel-ps-psf ....................................... SKIPPED
[INFO] angel-ps-graph ..................................... SKIPPED
[INFO] angel-ps-tools ..................................... SKIPPED
[INFO] angel-ps-mllib ..................................... SKIPPED
[INFO] angel-ps-examples .................................. SKIPPED
[INFO] spark-on-angel ..................................... SKIPPED
[INFO] spark-on-angel-core ................................ SKIPPED
[INFO] spark-on-angel-mllib ............................... SKIPPED
[INFO] spark-on-angel-graph ............................... SKIPPED
[INFO] spark-on-angel-examples ............................ SKIPPED
[INFO] angel-dist ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.039 s
[INFO] Finished at: 2020-11-13T12:11:32+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.igor-petruk.protobuf:protobuf-maven-plugin:0.6.3:run (default) on project angel-ps-core: Protobuf installation version does not match Protobuf library version -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :angel-ps-core

**Comment by ouyangwen-it** [comment]
Protobuf library version default is 2.5.0，if want other version，you can modify in pom and rebuild
