### ISSUE TITLE
LINE算法模型存储时，没有自动生成临时目录，导致模型结果存储失败

### ISSUE THREAD

**Issue by dongxuej** [Angel-ML/angel#1052]
LINE算法执行参数：
input=hdfs://jinrong-hadoop3-1v/home/hdp-jinrong-stargraph/fanqizha/subgraph/input/20191231/part-00000
output=hdfs://jinrong-hadoop3-1v/home/hdp-jinrong-stargraph/jiadongxue/angel/model/test_line/

source /home/work/software/angel/bin/spark-on-angel-env.sh
$SPARK_HOME/bin/spark-submit \
    --conf spark.ps.jars=$SONA_ANGEL_JARS \
    --conf spark.ps.instances=10 \
    --conf spark.ps.cores=1 \
    --conf spark.ps.memory=20g \
    --conf spark.executorEnv.JAVA_HOME=/home/yarn/software/java8 \
    --conf spark.yarn.appMasterEnv.JAVA_HOME=/home/yarn/software/java8 \
    --conf spark.dynamicAllocation.enabled=false \
    --jars $SONA_SPARK_JARS \
    --name "LINE-spark-on-angel-test" \
    --num-executors 100 \
    --executor-cores 1 \
    --executor-memory 6g \
    --class com.tencent.angel.spark.examples.cluster.LINEExample \
    /home/work/software/angel/lib/spark-on-angel-examples-3.1.0.jar \
    input:$input output:$output embedding:128 negative:5 epoch:10 stepSize:0.01 batchSize:1000 psPartitionNum:10 remapping:false order:2 sep:comma mode:yarn-client

结果：模型保存失败
报错原因：未自动创建临时文件夹
![image](https://user-images.githubusercontent.com/24312864/101893601-eaebcd80-3bdf-11eb-92da-0c1c0e4b64a8.png)

**Comment by ouyangwen-it** [comment]
临时目录是hdfs共享目录，你这边生成的是local目录了，指定下参数
