### ISSUE TITLE
How to estimate the model size?

### ISSUE THREAD

**Issue by catordog-byte** [Angel-ML/angel#1054]
Not sure if I understand this correctly. 
`word2vec模型大小的计算公式为： 词典大小 * Embedding特征的维度 * 2 * 4 Byte，比如说1kw节点、100维的配置下，模型大小差不多有60G大小` 
For 10M words, the total size should be: 10M * 100 * 2 * 4 => 8G?

https://github.com/Angel-ML/angel/blob/master/docs/algo/sona/word2vec_sona.md

**Comment by ouyangwen-it** [comment]
> Not sure if I understand this correctly.
> `word2vec模型大小的计算公式为： 词典大小 * Embedding特征的维度 * 2 * 4 Byte，比如说1kw节点、100维的配置下，模型大小差不多有60G大小`
> For 10M words, the total size should be: 10M * 100 * 2 * 4 => 8G?
> 
> https://github.com/Angel-ML/angel/blob/master/docs/algo/sona/word2vec_sona.md

文档那边描述有误，应该是10M * 100 * 2 * 4 = 8G，实际申请总内存的话大概16g就可以了
