### ISSUE TITLE
缺少com.tencent.angel.ml.core文件夹

### ISSUE THREAD

**Issue by EnjoyRenWei** [Angel-ML/angel#1061]
⁣example里面的类找不到com.tencent.angel.ml.core下面的类，我看了ml文件夹下没有core文件夹

**Comment by ouyangwen-it** [comment]
用的是哪个版本，具体是哪个类呢

**Comment by limingoo** [comment]
> ⁣example里面的类找不到com.tencent.angel.ml.core下面的类，我看了ml文件夹下没有core文件夹

兄弟，怎么解决的?
