### ISSUE TITLE
[Question] Stuck at 'yarn.Client: Application report for application_1619503327930_0017 (state: ACCEPTED)'

### ISSUE THREAD

**Issue by bidiudiu** [Angel-ML/angel#1065]
**Angel version : 3.1.0**
**Environment**:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=zh-CN style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

配置 | 信息
-- | --
CPU | Intel(R)   Xeon(R) CPU E5-2650 v3 @ 2.30GHz
System | Ubuntu16.04
Mem | 16GB
Disk | 2T

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=zh-CN style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

依赖 | 版本
-- | --
Protoc | 2.5.0
Spark | 2.4.7 Using Scala   version 2.11.12
Hadoop | 2.7.1
Python | 2.7.12
JDK | openjdk   version "1.8.0_292"
Maven | Apache   Maven 3.3.9

</div>

</body>

</html>

</div>

</body>

</html>

**Question**: 
根据文档设置了JAVA_HOME, SPARK_HOME, ANGEL_HOME, ANGEL_HDFS_HOME， 修改了spark-on-angl-env.sh并执行了source ./spark-on-angl-env.sh。然后试图run pagerank的sample（参考 [pagerank_on_sona](https://github.com/Angel-ML/angel/blob/master/docs/algo/sona/pagerank_on_sona.md)），使用的输入文件为空格分隔的一行行的srcId和dstId（来自[plato的一份小数据](https://github.com/Tencent/plato/blob/master/data/graph/v100_e2150_ua_c3.csv)），指令如下：

`
$SPARK_HOME/bin/spark-submit   --master yarn-cluster  --conf spark.ps.instances=1   --conf spark.ps.cores=1   --conf spark.ps.jars=$SONA_ANGEL_JARS   --conf spark.ps.memory=5g   --jars $SONA_SPARK_JARS    --driver-memory 5g   --num-executors 1   --executor-cores 4   --executor-memory 5g   --class com.tencent.angel.spark.examples.cluster.PageRankExample   ../lib/spark-on-angel-examples-3.1.0.jar input:hdfs://localhost:8020/user/input1/pagerank_input_1.csv output:hdfs://localhost:8020/user/output1 tol:0.01 :5 resetProp:0.15
`

输出的log如下：

Warning: Master yarn-cluster is deprecated since 2.0. Please use master "yarn" with specified deploy mode instead.
21/05/07 03:22:31 WARN util.Utils: Your hostname, suzvm-linux62 resolves to a loopback address: 127.0.1.1; using 10.190.148.78 instead (on interface eth0)
21/05/07 03:22:31 WARN util.Utils: Set SPARK_LOCAL_IP if you need to bind to another address
21/05/07 03:22:32 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
21/05/07 03:22:33 INFO client.RMProxy: Connecting to ResourceManager at /0.0.0.0:8032
21/05/07 03:22:34 INFO yarn.Client: Requesting a new application from cluster with 1 NodeManagers
21/05/07 03:22:34 INFO yarn.Client: Verifying our application has not requested more than the maximum memory capability of the cluster (8192 MB per container)
21/05/07 03:22:34 INFO yarn.Client: Will allocate AM container, with 5632 MB memory including 512 MB overhead
21/05/07 03:22:34 INFO yarn.Client: Setting up container launch context for our AM
21/05/07 03:22:34 INFO yarn.Client: Setting up the launch environment for our AM container
21/05/07 03:22:34 INFO yarn.Client: Preparing resources for our AM container
21/05/07 03:22:34 WARN yarn.Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
21/05/07 03:22:37 INFO yarn.Client: Uploading resource file:/tmp/spark-b21695a6-c940-4544-b1ec-283e62bb612d/__spark_libs__5059971510128640671.zip -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/__spark_libs__5059971510128640671.zip
21/05/07 03:22:39 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/spark-on-angel-examples-3.1.0.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/spark-on-angel-examples-3.1.0.jar
21/05/07 03:22:39 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/fastutil-7.1.0.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/fastutil-7.1.0.jar
21/05/07 03:22:39 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/htrace-core-2.05.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/htrace-core-2.05.jar
21/05/07 03:22:39 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/sizeof-0.3.0.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/sizeof-0.3.0.jar
21/05/07 03:22:39 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/kryo-shaded-4.0.0.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/kryo-shaded-4.0.0.jar
21/05/07 03:22:39 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/minlog-1.3.0.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/minlog-1.3.0.jar
21/05/07 03:22:39 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/memory-0.8.1.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/memory-0.8.1.jar
21/05/07 03:22:39 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/commons-pool-1.6.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/commons-pool-1.6.jar
21/05/07 03:22:39 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/netty-all-4.1.42.Final.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/netty-all-4.1.42.Final.jar
21/05/07 03:22:39 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/hll-1.6.0.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/hll-1.6.0.jar
21/05/07 03:22:39 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/json4s-jackson_2.11-3.2.11.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/json4s-jackson_2.11-3.2.11.jar
21/05/07 03:22:39 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/stream-2.7.0.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/stream-2.7.0.jar
21/05/07 03:22:39 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/jniloader-1.1.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/jniloader-1.1.jar
21/05/07 03:22:39 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/native_system-java-1.1.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/native_system-java-1.1.jar
21/05/07 03:22:40 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/arpack_combined_all-0.1.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/arpack_combined_all-0.1.jar
21/05/07 03:22:40 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/core-1.1.2.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/core-1.1.2.jar
21/05/07 03:22:40 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/netlib-native_ref-linux-armhf-1.1-natives.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/netlib-native_ref-linux-armhf-1.1-natives.jar
21/05/07 03:22:40 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/netlib-native_ref-linux-i686-1.1-natives.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/netlib-native_ref-linux-i686-1.1-natives.jar
21/05/07 03:22:40 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/netlib-native_ref-linux-x86_64-1.1-natives.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/netlib-native_ref-linux-x86_64-1.1-natives.jar
21/05/07 03:22:40 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/netlib-native_system-linux-armhf-1.1-natives.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/netlib-native_system-linux-armhf-1.1-natives.jar
21/05/07 03:22:40 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/netlib-native_system-linux-i686-1.1-natives.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/netlib-native_system-linux-i686-1.1-natives.jar
21/05/07 03:22:40 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/netlib-native_system-linux-x86_64-1.1-natives.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/netlib-native_system-linux-x86_64-1.1-natives.jar
21/05/07 03:22:40 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/angel-ps-graph-3.1.0.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/angel-ps-graph-3.1.0.jar
21/05/07 03:22:40 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/angel-ps-core-3.1.0.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/angel-ps-core-3.1.0.jar
21/05/07 03:22:40 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/angel-ps-psf-3.1.0.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/angel-ps-psf-3.1.0.jar
21/05/07 03:22:40 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/angel-ps-mllib-3.1.0.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/angel-ps-mllib-3.1.0.jar
21/05/07 03:22:40 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/spark-on-angel-mllib-3.1.0-ps.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/spark-on-angel-mllib-3.1.0-ps.jar
21/05/07 03:22:40 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/spark-on-angel-graph-3.1.0-ps.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/spark-on-angel-graph-3.1.0-ps.jar
21/05/07 03:22:40 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/spark-on-angel-core-3.1.0.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/spark-on-angel-core-3.1.0.jar
21/05/07 03:22:40 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/spark-on-angel-mllib-3.1.0.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/spark-on-angel-mllib-3.1.0.jar
21/05/07 03:22:40 INFO yarn.Client: Uploading resource file:/home/yize/angel/dist/target/angel-3.1.0-bin/lib/spark-on-angel-graph-3.1.0.jar -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/spark-on-angel-graph-3.1.0.jar
21/05/07 03:22:40 INFO yarn.Client: Uploading resource file:/tmp/spark-b21695a6-c940-4544-b1ec-283e62bb612d/__spark_conf__7730304021913002589.zip -> hdfs://localhost:9000/user/yanjun/.sparkStaging/application_1619503327930_0018/__spark_conf__.zip
21/05/07 03:22:40 INFO spark.SecurityManager: Changing view acls to: yanjun
21/05/07 03:22:40 INFO spark.SecurityManager: Changing modify acls to: yanjun
21/05/07 03:22:40 INFO spark.SecurityManager: Changing view acls groups to:
21/05/07 03:22:40 INFO spark.SecurityManager: Changing modify acls groups to:
21/05/07 03:22:40 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(yanjun); groups with view permissions: Set(); users  with modify permissions: Set(yanjun); groups with modify permissions: Set()
21/05/07 03:22:42 INFO yarn.Client: Submitting application application_1619503327930_0018 to ResourceManager
21/05/07 03:22:42 INFO impl.YarnClientImpl: Submitted application application_1619503327930_0018
21/05/07 03:22:43 INFO yarn.Client: Application report for application_1619503327930_0018 (state: ACCEPTED)
21/05/07 03:22:43 INFO yarn.Client:
         client token: N/A
         diagnostics: N/A
         ApplicationMaster host: N/A
         ApplicationMaster RPC port: -1
         queue: default
         start time: 1620382962755
         final status: UNDEFINED
         tracking URL: http://suzvm-linux62:8088/proxy/application_1619503327930_0018/
         user: yanjun
21/05/07 03:22:44 INFO yarn.Client: Application report for application_1619503327930_0018 (state: ACCEPTED)
21/05/07 03:22:45 INFO yarn.Client: Application report for application_1619503327930_0018 (state: ACCEPTED)
21/05/07 03:22:46 INFO yarn.Client: Application report for application_1619503327930_0018 (state: ACCEPTED)
21/05/07 03:22:47 INFO yarn.Client: Application report for application_1619503327930_0018 (state: ACCEPTED)
21/05/07 03:22:48 INFO yarn.Client: Application report for application_1619503327930_0018 (state: ACCEPTED)
21/05/07 03:22:49 INFO yarn.Client: Application report for application_1619503327930_0018 (state: ACCEPTED)
21/05/07 03:22:50 INFO yarn.Client: Application report for application_1619503327930_0018 (state: ACCEPTED)
21/05/07 03:22:51 INFO yarn.Client: Application report for application_1619503327930_0018 (state: ACCEPTED)
21/05/07 03:22:52 INFO yarn.Client: Application report for application_1619503327930_0018 (state: ACCEPTED)
21/05/07 03:22:53 INFO yarn.Client: Application report for application_1619503327930_0018 (state: ACCEPTED)
21/05/07 03:22:54 INFO yarn.Client: Application report for application_1619503327930_0018 (state: ACCEPTED)
......
......

然后就会一直卡在 ’yarn.Client: Application report for application_1619503327930_0018 (state: ACCEPTED)‘，等了几小时也还在这个状态。请问各位大佬，可能是什么问题？哪里设置不对？

**Comment by ouyangwen-it** [comment]
这个一般是申请不到资源，无法提交作业到集群，你可以检查下你集群配置，现在提交的队列是否有资源
