### ISSUE TITLE
give KCore result as graphx ConnectedComponents did

### ISSUE THREAD

**Issue by liangshi036** [Angel-ML/angel#1122]
now KCore gives vertice's k number as the example shows.

however, It would be helpful if the output give min vertices  id number which neibourhood it belongs to. the K result could be summary from it.

**Comment by xujie32** [comment]
Could you please show me a detailed example? For the given vertices A/B/C in the following graph, what do you mean by "min vertices id number which neibourhood it belongs to"  
![image](https://user-images.githubusercontent.com/6993809/124530030-51fff680-de3e-11eb-9d4b-58de93a9f24f.png)

**Comment by liangshi036** [comment]
as the images shows, the core=3 nodes would be in one community, but  it's not the good way to do community discovery simply using the K-core number. as the green and yellow nodes indicates. I'm gonna close the issue.
