### ISSUE TITLE
如何基于pyspark dataframe 使用 angel graph

### ISSUE THREAD

**Issue by wangbingnan136** [Angel-ML/angel#1194]
angel目前支持python语法吗？在issues里面看到了pyangel的介绍，但是文档里好像没有太多关于pyangel的使用说明

**Comment by ouyangwen-it** [comment]
> angel目前支持python语法吗？在issues里面看到了pyangel的介绍，但是文档里好像没有太多关于pyangel的使用说明

目前不支持python客户端了，python的话可以查看pytorch on angel项目
