### ISSUE TITLE
yarn-client模式下运行 cluster.LINEExample 用例，checkpoint 步骤报错

### ISSUE THREAD

**Issue by nanyoullm** [Angel-ML/angel#1235]
---
spark：2.1
hadoop：2.6
两台机器
---

脚本：
```
${SPARK_HOME}/bin/spark-submit --master yarn-client --conf spark.ps.jars=${SONA_ANGEL_JARS} --conf spark.ps.instances=2 --conf spark.ps.cores=2 --conf spark.ps.memory=2g --jars ${SONA_SPARK_JARS},/root/angel/lib/jettison-1.1.jar --queue default --driver-memory 1g --num-executors 4 --executor-cores 2 --executor-memory 1g --class com.tencent.angel.spark.examples.cluster.LINEExample /root/angel/spark-on-angel-examples-${ANGEL_VERSION}.jar input:$input output:$output
```

yarn-client模式下运行 cluster.LINEExample，任务卡在截图部分，请问是什么问题？路径下有文件，但是报错提示找不到
<img width="1072" alt="企业微信截图_1660724420233" src="https://user-images.githubusercontent.com/13297712/185070500-3f6b91e1-03cc-498d-8930-bb12c8af4b06.png">

**Comment by nanyoullm** [comment]
@paynie

**Comment by nanyoullm** [comment]
目前该项目没人维护了吗

**Comment by nanyoullm** [comment]
@leleyu 大佬有空看看吗

**Comment by ouyangwen-it** [comment]
<img width="954" alt="image" src="https://user-images.githubusercontent.com/13943417/185824543-f43110c7-d4fe-4edd-91d3-af3d5397a568.png">
checkpoint path要hdfs路径

**Comment by nanyoullm** [comment]
@ouyangwen-it 我想尝试下设置checkpoint path到hdfs，不过没有找到设置的地方，比如 LINE() 里没有找到对应参数，也许是 pscontext 里？

**Comment by ouyangwen-it** [comment]
> @ouyangwen-it 我想尝试下设置checkpoint path到hdfs，不过没有找到设置的地方，比如 LINE() 里没有找到对应参数，也许是 pscontext 里？

默认是根据你的output路径的hdfs前缀+/tmp/user路径，你输入输出填的是hdfs路径吗，如果是的话试试spark conf加上
spark.hadoop.fs.defaultFS=hdfs://namenodexxx/(你hdfs集群前缀) 跑下看看

**Comment by nanyoullm** [comment]
> 

实际上，脚本的输入input 和输出 output 已经是hdfs路径了，但是保存 checkpoint 的 tmp 并没有，所有报了如上的错
<img width="706" alt="1661246789849" src="https://user-images.githubusercontent.com/13297712/186123213-4a138f7f-6eac-4927-a4e7-51a85a7e9f11.png">

**Comment by nanyoullm** [comment]
> > @ouyangwen-it 我想尝试下设置checkpoint path到hdfs，不过没有找到设置的地方，比如 LINE() 里没有找到对应参数，也许是 pscontext 里？
> 
> 默认是根据你的output路径的hdfs前缀+/tmp/user路径，你输入输出填的是hdfs路径吗，如果是的话试试spark conf加上 spark.hadoop.fs.defaultFS=hdfs://namenodexxx/(你hdfs集群前缀) 跑下看看

实际上，脚本的输入input 和输出 output 已经是 hdfs 路径了，但是保存 checkpoint 的 tmp 并没有，所以报了如上的错

<img width="934" alt="1661246938877" src="https://user-images.githubusercontent.com/13297712/186123794-32db46c0-bbf9-42ba-929b-5a636c0ae8be.png">

无奈之举，在注释掉上图 106 行，同时确保 checkpointInterval 大于 epoch 的情况下，跳过 checkpoint 这步可以正常训练，结果输出到了 hdfs

**Comment by ouyangwen-it** [comment]
> > > @ouyangwen-it 我想尝试下设置checkpoint path到hdfs，不过没有找到设置的地方，比如 LINE() 里没有找到对应参数，也许是 pscontext 里？
> > 
> > 
> > 默认是根据你的output路径的hdfs前缀+/tmp/user路径，你输入输出填的是hdfs路径吗，如果是的话试试spark conf加上 spark.hadoop.fs.defaultFS=hdfs://namenodexxx/(你hdfs集群前缀) 跑下看看
> 
> 实际上，脚本的输入input 和输出 output 已经是 hdfs 路径了，但是保存 checkpoint 的 tmp 并没有，所以报了如上的错
> 
> <img alt="1661246938877" width="934" src="https://user-images.githubusercontent.com/13297712/186123794-32db46c0-bbf9-42ba-929b-5a636c0ae8be.png">
> 
> 无奈之举，在注释掉上图 106 行，同时确保 checkpointInterval 大于 epoch 的情况下，跳过 checkpoint 这步可以正常训练，结果输出到了 hdfs
应该是客户端拿不到你的defaultFS，你可以试试spark conf加上 spark.hadoop.fs.defaultFS配置

**Comment by nanyoullm** [comment]
> 

@ouyangwen-it 试了下，这个方法是可以的，谢谢提醒
