### ISSUE TITLE
Possible Word2Vec optimization

### ISSUE THREAD

**Issue by EvgenyZamyatin** [Angel-ML/angel#1238]
Hi!
What do you think about such Word2Vec optimization:
Let's draw negative samples within single parameter-server partition. In that case, instead of getting vectors for negative samples, we can pass src word vector to that partition. At this partition we can update out-matrix for negatives and calculate grads for src embedding. In response to the executor we can return this gradient update.
Thus we can reduce network communication by N negative samples multiplier.

**Comment by ouyangwen-it** [comment]
> Hi! What do you think about such Word2Vec optimization: Let's draw negative samples within single parameter-server partition. In that case, instead of getting vectors for negative samples, we can pass src word vector to that partition. At this partition we can update out-matrix for negatives and calculate grads for src embedding. In response to the executor we can return this gradient update. Thus we can reduce network communication by N negative samples multiplier.

Yes, we have tried this optimization method. Negative sampling in the ps partition can indeed reduce communication, but the effect of the ps partition local negative sampling model is not as good as that of global negative sampling.

**Comment by EvgenyZamyatin** [comment]
Thanks for the answer! Such idea is described in a yahoo paper "Distributed Negative Sampling For Word Embeddings"
