### ISSUE TITLE
LINEModel训练时，每个epoch只训练一个batch？

### ISSUE THREAD

**Issue by nanyoullm** [Angel-ML/angel#1239]
从代码上看？LINE训练时，对于每轮epoch，只取了一个batch进行训练吗
<img width="1027" alt="1661927449277" src="https://user-images.githubusercontent.com/13297712/187609254-3e9b41a0-7168-456e-bc2d-24bd2eebac87.png">

代码位置：https://github.com/Angel-ML/angel/blob/0c3162d55a22dc97a4c657e66b26695a06510a52/spark-on-angel/graph/src/main/scala/com/tencent/angel/graph/embedding/line/LINEModel.scala#L109

**Comment by nanyoullm** [comment]
@ouyangwen-it

**Comment by nanyoullm** [comment]
看了源码，应该是这样理解：
`trainBatches`由`LINEModel.buildDataBatches()`获得，`trainBatches`的`next()`其实是固定返回整个shuffle后的数据集；整个数据集的每个分区中，返回把数据切成若干batchsize大小的iterator

**Comment by ouyangwen-it** [comment]
> 看了源码，应该是这样理解： `trainBatches`由`LINEModel.buildDataBatches()`获得，`trainBatches`的`next()`其实是固定返回整个shuffle后的数据集；整个数据集的每个分区中，返回把数据切成若干batchsize大小的iterator

对的，每轮训练全部数据，minibatch方式
