### ISSUE TITLE
Is there any plan to implement word2vec ？

### ISSUE THREAD

**Issue by clcron** [Angel-ML/angel#270]

**Comment by andyyehoo** [comment]
We are working on it now. Please wait~

**Comment by EmbedXj** [comment]
Can we know the implementation of word2vec when will be finished ?

**Comment by crackcell** [comment]
How is the progress, plz ? @andyyehoo

**Comment by weiwee** [comment]
Included in the new version to be released this month~ @crackcell

**Comment by haoyangOxford** [comment]
I'm trying to submit a job to my spark/hadoop cluster for training word2vec, is there an example angle-submit command to help me get started? thanks! @weiwee

**Comment by haoyangOxford** [comment]
@ZunwenYou Could you please provide an angel-submit demo using some example data, so that I can try the word2vec on my yarn cluster? Thank you.
