### ISSUE TITLE
conflict with hadoop-2.6.0-cdh

### ISSUE THREAD

**Issue by bravecharge** [Angel-ML/angel#303]
angel can be compiled success  with apache-hadoop-2.6.0 but cdh-hadoop-2.6.0.
I found a solution:
append the following code to  

> angel-ps\core\src\main\java\com\tencent\angel\worker\task\MRTaskContext.java

```
public boolean userClassesTakesPrecedence() {
	return false;
}
```

**Comment by paynie** [comment]
Thanks for this issue, We will test angel with cdh hadoop in next version
