### ISSUE TITLE
java.lang.IllegalArgumentException: Can not create a Path from an empty string

### ISSUE THREAD

**Issue by liuzx32** [Angel-ML/angel#315]
安装提示安装配置好angel-1.5.0之后，提交SOAN-example-local测试任务，提示上述异常

**Comment by ZunwenYou** [comment]
Flow this [Spark on Angel Tutorial]( https://github.com/Tencent/angel/blob/master/docs/tutorials/spark_on_angel_quick_start.md), and finish the configuration in spark-on-angel-env.sh,

**Comment by Tongzhenguo** [comment]
我也遇到了同样的问题，这个我的spark-on-angel-env.sh配置：
export SPARK_HOME=$SPARK2_HOME
#echo $SPARK_HOME
export ANGEL_HOME=/data/dmp/angel-1.5.0
export ANGEL_HDFS_HOME=hdfs://nameservice/data/dmp/angel-1.5.0
export ANGEL_VERSION=1.5.0

这是source bin/spark-on-angel-env.sh的输出：
[impala@node1.azkaban.bigdata.dmp.com bin]$source spark-on-angel-env.sh    
/data/dmp/cloudera/parcels/SPARK2/lib/spark2
SONA_ANGEL_JARS: hdfs://nameservice/data/dmp/angel-1.5.0/lib/fastutil-7.1.0.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/htrace-core-2.05.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/sizeof-0.3.0.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/kryo-shaded-4.0.0.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/minlog-1.3.0.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/sketches-core-0.8.1.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/memory-0.8.1.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/commons-pool-1.6.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/angel-ps-core-1.5.0.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/angel-ps-mllib-1.5.0.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/angel-ps-examples-1.5.0.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/angel-ps-psf-1.5.0.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/spark-on-angel-mllib-1.5.0-ps.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/spark-on-angel-examples-1.5.0-ps.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/scala-library-2.11.8.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/fastutil-7.1.0.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/htrace-core-2.05.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/sizeof-0.3.0.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/kryo-shaded-4.0.0.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/minlog-1.3.0.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/sketches-core-0.8.1.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/memory-0.8.1.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/commons-pool-1.6.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/angel-ps-core-1.5.0.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/angel-ps-mllib-1.5.0.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/angel-ps-examples-1.5.0.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/angel-ps-psf-1.5.0.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/spark-on-angel-mllib-1.5.0-ps.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/spark-on-angel-examples-1.5.0-ps.jar,hdfs://nameservice/data/dmp/angel-1.5.0/lib/scala-library-2.11.8.jar
SONA_SPARK_JARS: /data/dmp/angel-1.5.0/lib/fastutil-7.1.0.jar,/data/dmp/angel-1.5.0/lib/htrace-core-2.05.jar,/data/dmp/angel-1.5.0/lib/sizeof-0.3.0.jar,/data/dmp/angel-1.5.0/lib/kryo-shaded-4.0.0.jar,/data/dmp/angel-1.5.0/lib/minlog-1.3.0.jar,/data/dmp/angel-1.5.0/lib/sketches-core-0.8.1.jar,/data/dmp/angel-1.5.0/lib/memory-0.8.1.jar,/data/dmp/angel-1.5.0/lib/commons-pool-1.6.jar,/data/dmp/angel-1.5.0/lib/angel-ps-core-1.5.0.jar,/data/dmp/angel-1.5.0/lib/angel-ps-mllib-1.5.0.jar,/data/dmp/angel-1.5.0/lib/angel-ps-examples-1.5.0.jar,/data/dmp/angel-1.5.0/lib/angel-ps-psf-1.5.0.jar,/data/dmp/angel-1.5.0/lib/spark-on-angel-core-1.5.0.jar,/data/dmp/angel-1.5.0/lib/spark-on-angel-mllib-1.5.0.jar,/data/dmp/angel-1.5.0/lib/fastutil-7.1.0.jar,/data/dmp/angel-1.5.0/lib/htrace-core-2.05.jar,/data/dmp/angel-1.5.0/lib/sizeof-0.3.0.jar,/data/dmp/angel-1.5.0/lib/kryo-shaded-4.0.0.jar,/data/dmp/angel-1.5.0/lib/minlog-1.3.0.jar,/data/dmp/angel-1.5.0/lib/sketches-core-0.8.1.jar,/data/dmp/angel-1.5.0/lib/memory-0.8.1.jar,/data/dmp/angel-1.5.0/lib/commons-pool-1.6.jar,/data/dmp/angel-1.5.0/lib/angel-ps-core-1.5.0.jar,/data/dmp/angel-1.5.0/lib/angel-ps-mllib-1.5.0.jar,/data/dmp/angel-1.5.0/lib/angel-ps-examples-1.5.0.jar,/data/dmp/angel-1.5.0/lib/angel-ps-psf-1.5.0.jar,/data/dmp/angel-1.5.0/lib/spark-on-angel-core-1.5.0.jar,/data/dmp/angel-1.5.0/lib/spark-on-angel-mllib-1.5.0.jar

**Comment by datawlb** [comment]
这个问题大家有解决了吗？我用的angel-3.1.0同样遇到这个问题
