### ISSUE TITLE
设置了树的大小是10，但是迭代次数一直是100，而且任务的迭代次数超过了100, 请问是什么原因？

### ISSUE THREAD

**Issue by drfilter** [Angel-ML/angel#350]
以下是参数配置
`-Dangel.am.log.level=INFO \
-Dangel.ps.log.level=INFO \
-Dangel.worker.log.level=INFO \
-Dangel.app.submit.class=com.tencent.angel.ml.GBDT.GBDTRunner \
-Daction.type=train  \
-Dangel.ml.data.type=libsvm \
-Dml.validate.ratio=0.1 \
-Dml.feature.num=64501 \
eDml.feature.nnz=20 \
-Dml.gbdt.cate.feat=none \
-Dml.gbdt.tree.num=10 \
-Dml.gbdt.tree.depth=6 \
-Dml.gbdt.split.num=10 \
-Dml.gbdt.sample.ratio=1.0 \
-Dml.learn.rate=0.01 \
-Dml.gbdt.server.split=true \
-Dml.compress.bytes=2 \
-Dangel.train.data.path=$input_path \
-Dangel.save.model.path=$model_path \
-Dangel.workergroup.number=50 \
-Dangel.worker.memory.mb=6000 \
-Dangel.task.data.storage.level=memory \
-Dangel.worker.task.number=1 \
-Dangel.ps.number=50 \
-Dangel.ps.memory.mb=6000 \`

以下是spark运行信息
![image](https://user-images.githubusercontent.com/1189926/40696524-c5310ae0-63f8-11e8-83ff-a26cb6fcf519.png)

**Comment by bluesjjw** [comment]
请问是不是client里的迭代论数，这个迭代数不等于树的数量

worker日志里有更详细的信息，请问是否可以贴一下worker日志？

**Comment by drfilter** [comment]
看起来确实不是树的数量，不明白这里的100表示什么？
