### ISSUE TITLE
请问Async mini-batch FTRL 参数如何更新

### ISSUE THREAD

**Issue by QueenOfGalaxy** [Angel-ML/angel#374]

**Comment by luxin0123** [comment]
Hello, thanks for your question @QueenOfGalaxy .The trainning process  in each batch of async mini-batch FTRL is as  this: 
1. Each workers first pull the model z and n in to local according to their local sample indexs.
2. Then the worker compute the gradient of each sample in the batch as well as the corresponding increment of z and n.
3. Sum all of the increment of z and n which will be organized as two vector (each for z model and each for n model).
4. Push these increment vectors to ps to add with corresponding model no matter other workers whether have finished their gradient and push process.

**Comment by kiminh** [comment]
@luxin0123 @paynie  Hi, I want to know the implementation of "com.tencent.angel.spark.ml.online_learning.FTRL" is BSP or SSP? intuitively, i think it's BSP?
