### ISSUE TITLE
Does Spark-on-Angel support SSP?

### ISSUE THREAD

**Issue by luzengxiang** [Angel-ML/angel#401]
Does Spark-on-Angel support SSP?

**Comment by leleyu** [comment]
Currently Spark-on-Angel cannot run with SSP. The default protocol is BSP. You can also use ASP by calling pull/push inside each stage manually.

**Comment by kiminh** [comment]
Hi, I want to know the implementation of "com.tencent.angel.spark.ml.online_learning.FTRL" is BSP or SSP? intuitively, i think it's BSP?
