### ISSUE TITLE
Does angel-LDA* learn better topics than Peacock?

### ISSUE THREAD

**Issue by ericxsun** [Angel-ML/angel#428]
As I know, Tencent published a paper which introduced a system named as [Peacock](https://arxiv.org/abs/1405.4402) in 2014. In that paper, it showed amazing results on topic inference( training on huge dataset and learning large topics-greater than 10^5). So I'm wonder and interested in the topic modeling performance of `angel-LDA*`. Is that better than Peacock? And can it also learn the long-tail topics?

Thanks a lot.

**Comment by zhangyafeikimi** [comment]
Peacock is a closed source software.
