### ISSUE TITLE
compile fail:

### ISSUE THREAD

**Issue by zhaochunhua** [Angel-ML/angel#430]
Could not resolve dependencies for project com.tencent.angel:angel-ps:pom:2.0.0-alpha
the log as follow:

> [INFO] angel .............................................. SUCCESS [  0.222 s]
> [INFO] angel-ps ........................................... FAILURE [01:06 min]
> [INFO] angel-ps-core ...................................... SKIPPED
> [INFO] angel-ps-psf ....................................... SKIPPED
> [INFO] angel-ps-tools ..................................... SKIPPED
> [INFO] angel-ps-mllib ..................................... SKIPPED
> [INFO] angel-ps-examples .................................. SKIPPED
> [INFO] spark-on-angel ..................................... SKIPPED
> [INFO] spark-on-angel-core ................................ SKIPPED
> [INFO] spark-on-angel-mllib ............................... SKIPPED
> [INFO] spark-on-angel-examples ............................ SKIPPED
> [INFO] angel-dist ......................................... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 01:07 min
> [INFO] Finished at: 2018-10-12T13:07:28+08:00
> [INFO] Final Memory: 13M/226M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project angel-ps: Could not resolve dependencies for project com.tencent.angel:angel-ps:pom:2.0.0-alpha: The following artifacts could not be resolved: org.json4s:json4s-jackson_2.11:jar:3.4.2, com.google.code.gson:gson:jar:2.8.5: Could not find artifact org.json4s:json4s-jackson_2.11:jar:3.4.2 in weibo (http://redmine.intra.weibo.com:8081/nexus/content/groups/public) -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <goals> -rf :angel-ps

**Comment by zhaochunhua** [comment]
change other branch, don't have this problem

**Comment by JessicaAlphy** [comment]
which branch do you download?
