### ISSUE TITLE
如何使用 model

### ISSUE THREAD

**Issue by yliu-dev** [Angel-ML/angel#432]
job1 :一个在线job
learner.train(streams, model, 1)
model.save("/opt/amodel/test/")

我实时训练出了一个 LogisticRegression 的model
但是 不知道如何使用 这个model 来预测 新的数据

job2： 希望能在系统中直接使用这个model
 val model = GraphModel(className)
    model.load("/opt/amodel/test/")
    val learner = new OfflineLearner()

有没有什么方法 能使用model 直接去predict 一条数据

**Comment by Phoenixinfire** [comment]
同问啊

**Comment by leleyu** [comment]
We are developing the load/save model interfaces and the model servering function.
We will release this version soon.
