### ISSUE TITLE
obvious bug in SONA

### ISSUE THREAD

**Issue by Esail** [Angel-ML/angel#510]
In GraphModel:

def init(taskNum: Int): Unit = {
    network()

    graph.taskNum = taskNum
    graph.createMatrices()
    graph.init()
    println(s"graph=\n$graph")
  }

 graph.createMatrices() ==>

  /**
    * Create matrices contain in the model, this method is only used in **Worker/Executor**
    */
  def createMatrices(): Unit = {
    PSMatrixUtils.createPSMatrix(matrixCtxs)
  }

however, in JSonRunner:

  // init model here
    model.init(data.getNumPartitions)

So Driver is initialing a method that is marked as only used in executor.

**Comment by leleyu** [comment]
Thanks for this question. 
``graph.createMatrices()‘’ can be used both on worker and driver.
Here we create the matrices on driver and pass the graph structure (which contains the matrix_ids of all matrices) to workers through the broadcast interface of Spark.
Then each worker can access the matrices on PS through these matrix_ids.
