### ISSUE TITLE
请问如何使得angel在hadoop3.1.0的平台上跑

### ISSUE THREAD

**Issue by yang3808282** [Angel-ML/angel#564]
请问，我想让angel支持hadoop3.1.0的平台，我应该如何修改angel源码，或者有没有大神编译好了支持hadoop3.1.0的安装包，分享下

**Comment by ouyangwen-it** [comment]
> 请问，我想让angel支持hadoop3.1.0的平台，我应该如何修改angel源码，或者有没有大神编译好了支持hadoop3.1.0的安装包，分享下

您好，支持hadoop3需要替换一些接口，我把diff文件给你，你修改下代码，编译打包就可以跑了。
[support hadoop3.txt](https://github.com/Angel-ML/angel/files/2655621/support.hadoop3.txt)
