### ISSUE TITLE
如果训练数据存储在很多文件夹下面，怎么设置才能让angel逐个读取，并进行训练？

### ISSUE THREAD

**Issue by Ross-Fan** [Angel-ML/angel#577]
例如，训练和测试的数据都是按照 date/hour/ 来存储的，那么在设置angel输入路径的时候，应该怎么设置 --angel.train.data.path，才能让angel逐个读取文件夹下面的数据，并进行训练，针对这些数据训练出一个模型，而不是读一个文件夹下的数据就训练一个模型

$ANGEL_HOME/bin/angel-submit \
     --action.type train \
     --angel.app.submit.class com.tencent.angel.ml.classification.lr.LRRunner  \
     --angel.train.data.path $train_path \
     --angel.save.model.path $model_path \
     --angel.log.path $log_path \
     --ml.sgd.batch.num 10000 \
     --ml.validate.ratio 0.1 \
     --ml.reg.l2 0 \

**Comment by paynie** [comment]
Do you mean that you need to read the files in all subdirectories?

**Comment by paynie** [comment]
you can try this: set mapreduce.input.fileinputformat.input.dir.recursive=true

**Comment by Ross-Fan** [comment]
Yes, my files stored as ../data0/hour0, ../data1/hour1 ,

> Do you mean that you need to read the files in all subdirectories?

yes, my file stored as ../data0/hour0, ../data1/hour1
I want the angel could read all the subdirectories

**Comment by Ross-Fan** [comment]
> you can try this: set mapreduce.input.fileinputformat.input.dir.recursive=true

why do I need to set this parameter?
angel read the input file via MapReduce?

**Comment by paynie** [comment]
Angel use the inputformat interface in MapReduce to define the data files format and split the data files

**Comment by Ross-Fan** [comment]
> Angel use the inputformat interface in MapReduce to define the data files format and split the data files

Thanks
