### ISSUE TITLE
can not find or load com.tencent.angel.master.AngelApplicationMaster

### ISSUE THREAD

**Issue by lijiajia** [Angel-ML/angel#621]
spark.log里的出错信息如下：
ERROR com.tencent.angel.client.yarn.AngelYarnClient: submit application to yarn failed

ps日志里面出错如下：
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=100M; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=200M; support was removed in 8.0
Error: Could not find or load main class com.tencent.angel.master.AngelApplicationMaster

**Comment by weiwee** [comment]
seems ps can't find angel-ps-${version}.jar, 
try upload lib/ to hdfs and then specify the corresponding path in the configuration file in bin/spark-on-angel-env.sh according to [https://github.com/Angel-ML/angel/blob/master/docs/tutorials/spark_on_angel_quick_start.md](tutorials)

**Comment by lijiajia** [comment]
If I add angel-ps-core-2.0.0.jar and angel-ps-mllib2.0.0.jar. It will get a "Can not find IntRangePartitioner" error

**Comment by lijiajia** [comment]
AngelApplicationMaster is in my jar

com/tencent/angel/master/task/
com/tencent/angel/master/task/AMTask.class
com/tencent/angel/master/task/TaskCounter.class
com/tencent/angel/master/task/AMTaskIterationState.class
com/tencent/angel/master/task/AMTaskManager.class
com/tencent/angel/master/task/AMTaskState.class
com/tencent/angel/master/task/AMTask$1.class
com/tencent/angel/master/AngelApplicationMaster.class
com/tencent/angel/master/HeartbeatMonitor$1.class
com/tencent/angel/master/MasterService.class
