### ISSUE TITLE
word2vec on yarn deployment doc 

### ISSUE THREAD

**Issue by haoyang09** [Angel-ML/angel#644]
Is there a doc of an example angle-submit for training word2vec? Also I couldn't find a config_details.md for the word2vec model. Thanks for help in advance!

**Comment by leleyu** [comment]
Word2vec is implemented on spark-on-angel. You can find the example from https://github.com/Angel-ML/angel/blob/master/spark-on-angel/examples/src/main/scala/com/tencent/angel/spark/examples/cluster/Word2vecExample.scala

**Comment by haoyang09** [comment]
I have tried to submit a job using the Word2vecExample following command, and got the following error. Any idea? Thanks!
`./angel-submit --angel.app.submit.class com.tencent.angel.ml.core.graphsubmit.GraphRunner --angel.train.data.path "hdfs://ec2-35-155-171-170.us-west-2.compute.amazonaws.com:9000/tmp/word2vec/input/"  --angel.log.path "hdfs://ec2-35-155-171-170.us-west-2.compute.amazonaws.com:9000/tmp/word2vec/w2v_log" --angel.save.model.path "hdfs://ec2-35-155-171-170.us-west-2.compute.amazonaws.com:9000/tmp/word2vec/w2v_model"  --action.type train  --ml.model.class.name com.tencent.angel.spark.examples.cluster.Word2VecExample  --angel.am.memory.gb 4  --angel.worker.memory.gb 4  --angel.ps.memory.gb 8 --angel.ps.number 2 --angel.ps.log.level DEBUG`


SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/ubuntu/angel/dist/target/angel-2.0.1-bin/lib/slf4j-log4j12-1.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
19/01/28 13:31:46 INFO utils.AngelRunJar: angelHomePath conf path=/home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//conf/angel-site.xml
19/01/28 13:31:46 INFO utils.AngelRunJar: load system config file success
19/01/28 13:31:46 INFO utils.AngelRunJar: jars loaded: file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/jniloader-1.1.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/native_system-java-1.1.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/arpack_combined_all-0.1.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/all-1.1.2.pom,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/core-1.1.2.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/netlib-native_ref-linux-armhf-1.1-natives.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/netlib-native_ref-linux-i686-1.1-natives.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/netlib-native_ref-linux-x86_64-1.1-natives.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/netlib-native_system-linux-armhf-1.1-natives.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/netlib-native_system-linux-i686-1.1-natives.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/netlib-native_system-linux-x86_64-1.1-natives.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/jackson-annotations-2.6.0.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/jackson-core-2.6.7.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/jackson-core-asl-1.8.8.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/jackson-databind-2.6.7.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/jackson-jaxrs-1.8.3.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/jackson-mapper-asl-1.8.8.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/jackson-module-paranamer-2.6.5.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/jackson-module-scala_2.11-2.6.5.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/jackson-xc-1.8.3.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/json4s-ast_2.11-3.4.2.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/json4s-core_2.11-3.4.2.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/json4s-jackson_2.11-3.4.2.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/json4s-scalap_2.11-3.4.2.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/netty-all-4.1.1.Final.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/angel-ps-mllib-2.0.1.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/angel-ps-tools-2.0.1.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/scala-reflect-2.11.8.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/memory-0.8.1.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/sketches-core-0.8.1.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/commons-pool-1.6.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/kryo-shaded-4.0.0.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/kryo-serializers-0.42.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/scala-library-2.11.8.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/angel-ps-core-2.0.1.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/angel-ps-psf-2.0.1.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/fastutil-7.1.0.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/sizeof-0.3.0.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/minlog-1.3.0.jar,file:///home/ubuntu/angel/dist/target/angel-2.0.1-bin/bin/..//lib/breeze_2.11-0.13.jar
19/01/28 13:31:46 INFO utils.AngelRunJar: angel python file: null
19/01/28 13:31:46 INFO utils.UGITools: UGI_PROPERTY_NAME is null 
19/01/28 13:31:46 INFO utils.AngelRunJar: submitClass: com.tencent.angel.ml.core.graphsubmit.GraphRunner
19/01/28 13:31:47 INFO conf.SharedConf: inctrain does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: train does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: ml.gbdt.max.node.num does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: train.loss does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: predict does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: validate.loss does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: log.likelihood does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: train.error does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: validate.error does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel-default.xml does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel-site.xml does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel. does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.am. does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.worker. does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.ps. does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.task. does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.workergroup. does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.train.data.path does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.predict.data.path does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.job.input.path does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.predict.out.path does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.serving.temp.path does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.serving.client.type does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.save.model.path does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.log.path does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.load.model.path does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.job.jar does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.ml.conf does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.job.libjars does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: queue does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.app.config.file does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.job.cache.archives does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.job.cache.files does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.job.complete.cancel.delegation.tokens does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.job.submit.host does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.job.submit.host.address does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.submit.user.name does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.job.dir does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.app.user.resource.files does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.app.serilize.state.file does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.output.path does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.tmp.output.path.prefix does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.tmp.output.path does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: ANGEL does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.jobid does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: job.xml does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.cluster.local.dir does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.workergroup.actual.number does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.worker.env does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.worker.java.opts does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.worker.heartbeat.interval.ms does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.workergroup.failed.tolerate does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.worker.max-attempts does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.task.actual.number does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.ps.backup.matrices does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.ps.max-attempts does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.ps.child.opts does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.ps.partition.class does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.matrixtransfer.max.requestnum does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.psagent. does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.ps.ip.list does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.psagent.java.opts does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.psagent.iplist does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.model.parse.name does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.parse.model.path does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: ml.connection.timeout does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: netty.server.io.threads does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: netty.io.mode does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: netty.client.io.threads does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: ml.rpc.timeout does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.app.type does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.pyangel.python does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.pyangel.pyfile does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.pyangel.pyfile.dependencies does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.plugin.service.enable does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.serving.sharding.num does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.serving.sharding.concurrent.capacity does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.serving.sharding.model.class does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.serving.master.ip does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.serving.master.port does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.serving.model.name does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.serving.model.load.timeout.minute does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.serving.model.load.check.inteval.second does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.serving.model.load.type does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: angel.serving.predict.local.output does not have default value!
19/01/28 13:31:47 INFO conf.SharedConf: [I@17f9d882 does not have default value!
19/01/28 13:31:47 ERROR utils.AngelRunJar: submit job failed 
java.lang.reflect.UndeclaredThrowableException
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1773)
	at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:56)
	at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:40)
Caused by: java.lang.ClassNotFoundException: com.tencent.angel.spark.examples.cluster.Word2VecExample
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.tencent.angel.ml.core.graphsubmit.GraphModel$.apply(GraphModel.scala:174)
	at com.tencent.angel.ml.core.graphsubmit.GraphRunner.train(GraphRunner.scala:48)
	at com.tencent.angel.ml.core.MLRunner$class.submit(MLRunner.scala:88)
	at com.tencent.angel.ml.core.graphsubmit.GraphRunner.submit(GraphRunner.scala:29)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:69)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:56)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	... 2 more

**Comment by leleyu** [comment]
word2vec is implemented on spark-on-angel not angel. You can run spark-on-angel with the way of spark-submit by first calling spark-on-angel-env.sh.
