### ISSUE TITLE
Angel on Spark GBDT regression task seems to conflict with ml.class.num param

### ISSUE THREAD

**Issue by Sherry-Xiaoyan-Zhang** [Angel-ML/angel#711]
Hi, 
I am running Angel on Spark GBDT for a regression task, however, it throws a GBDTException: 
`com.tencent.angel.spark.ml.tree.exception.GBDTException: More than 2 labels are provided:`
I did set `ml.gbdt.loss.func:rmse ml.gbdt.eval.metric:rmse`, so I think GBDTTrainer should not call ensureLabel, since it is a regression task.

**Comment by bluesjjw** [comment]
Sorry that GBDT currently supports classification.
But we implement RMSE for extension.
If you need regression, please submit an issue. We will handle this a.s.s.p.

**Comment by Sherry-Xiaoyan-Zhang** [comment]
Thanks, a new issue was submitted. https://github.com/Angel-ML/angel/issues/712
