### ISSUE TITLE
对于LR/FM这些算法graph.json怎么写?如果没有Serving端怎么加载？

### ISSUE THREAD

**Issue by mattxia** [Angel-ML/angel#723]
https://github.com/Angel-ML/angel/blob/master/docs/basic/json_conf.md
看文档里面说不支持，但是看serving自带的例子里面有https://github.com/Angel-ML/serving/tree/master/models/angel/lr  LR的graph..json

请问Serving加载模型是不是都需要graph.json？对于FM这种怎么生成graph.json?? thanks

HOw can I generate a graph.json for a FM or LR model, cause in the https://github.com/Angel-ML/angel/blob/master/docs/basic/json_conf.md ,which says only deep models support json, then how can I generate a json for FM,LR model, or else how can serving load the model.

**Comment by wangcaihua** [comment]
you need not care about json, because it will generate a graph.json file when you save model.

Note: this feature is now in experiment, so it in hotfix branch

**Comment by mattxia** [comment]
Got it, thanks.
