### ISSUE TITLE
angel/docs/algo/sona/feature_gbdt_sona.md  GBDT的问题

### ISSUE THREAD

**Issue by 1mrliu** [Angel-ML/angel#731]
上边写的是一阶二阶直方图，但是原始的GBDT是没有二阶的吧。lightgbm才有二阶吧？

**Comment by bluesjjw** [comment]
从XGBoost开始，就都有二阶直方图了，我们的实现也有的。

**Comment by 1mrliu** [comment]
Xgboost是有的   gbdt的二阶直方图，代价函数里边不能看出这个吧

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Jiawei <notifications@github.com>
发送时间: Wednesday, April 17, 2019 7:39:27 PM
收件人: Angel-ML/angel
抄送: liudong; Author
主题: Re: [Angel-ML/angel] angel/docs/algo/sona/feature_gbdt_sona.md GBDT的问题 (#731)


从XGBoost开始，就都有二阶直方图了，我们的实现也有的。

―

**Comment by bluesjjw** [comment]
代价函数里是看不出，泰勒展开之后就有了一阶和二阶梯度，xgboost的论文里有详细推导。

**Comment by 1mrliu** [comment]
XGB里边有二阶的  GBDT也属于xgb中的  这个地方弄清楚了 谢谢了

在2019年04月18日 15:55，Jiawei<notifications@github.com><mailto:notifications@github.com> 写道：

代价函数里是看不出，泰勒展开之后就有了一阶和二阶梯度，xgboost的论文里有详细推导。
