### ISSUE TITLE
Java.lang.ArrayIndexOutOfBoundsException:5600 occured after epoch{0} when trainning daw model

### ISSUE THREAD

**Issue by MissDinosaur** [Angel-ML/angel#806]
I tried to train a daw model with a ctr dataset whose data format is libsvm and feature size is 813, not including label column. In addition, the raw data of this ctr dataset has 28 fields, not including label field as well. I have set numfiled equal to 28, indexrange equal to 813, modeltype  as "T_DOUBLE_SPARSE", modelsize equal to 813, numfactors = 8 with outputdim = 8*28=224 in embedding layer, in daw_conf.json. But Java.lang.ArrayIndexOutOfBoundsException:5600 has occured after epoch{0} when I run this train. 
![image](https://user-images.githubusercontent.com/48971343/61760624-be72be00-adfe-11e9-89c4-3b9a12ccdbae.png)
![image](https://user-images.githubusercontent.com/48971343/61760697-f67a0100-adfe-11e9-9646-79fbedaf1e7f.png)
![image](https://user-images.githubusercontent.com/48971343/61760734-10b3df00-adff-11e9-8c50-ff0887289cb1.png)

**Comment by MissDinosaur** [comment]
Then I looked up for the reason in Angel sorce codes. And I have found  the program stepped into if- statement where row.isDense is TRUE. However I have set the modeltype as "T_DOUBLE_SPARSE", how could it step into this if-statement. I have no idea.
![20190724-104719(eSpace)](https://user-images.githubusercontent.com/48971343/61761159-70f75080-ae00-11e9-9420-9283c26c666a.png)
And code 822 implied that the array "values" had index out of bounds. Is there something wrong in my daw_conf.json, which has caused this error?  
Hope your help! THX!

**Comment by MissDinosaur** [comment]
My ctr dataset has the libsvm format like: 0.0 2:1.0 7:1.0 12:1.0 ...

**Comment by MissDinosaur** [comment]
Here is my submit: 
![image](https://user-images.githubusercontent.com/48971343/61762074-65595900-ae03-11e9-97ca-c8e1da596796.png)

**Comment by paynie** [comment]
If you use sparse model type but the model is small or very dense, angel will transfer to dense model type is PS for better performance

**Comment by MissDinosaur** [comment]
I have resolved this problem with the help of others. It's the reason that param numfield is wrong. Param numfield is the number of field of your input dataset which has been preprocessed before. So param numfield could not be the number of feature of your raw data which had not been preprocessed. After I corrected this fault and ensured my dataset did not exist a row data that field number was not equal to 7, then eveything has been ok.

**Comment by MissDinosaur** [comment]
> If you use sparse model type but the model is small or very dense, angel will transfer to dense model type is PS for better performance

Thank you, I got it.

**Comment by MissDinosaur** [comment]
> I have resolved this problem with the help of others. It's the reason that param numfield is wrong. Param numfield is the number of field of your input dataset which has been preprocessed before. So param numfield could not be the number of feature of your raw data which had not been preprocessed. After I corrected this fault and ensured my dataset did not exist a row data that field number was not equal to 7, then eveything has been ok.
