### ISSUE TITLE
word2vec train with all the embedding NAN as a result

### ISSUE THREAD

**Issue by wqh17101** [Angel-ML/angel#815]
mapping:
![image](https://user-images.githubusercontent.com/26429138/62339822-f9b47180-b50f-11e9-81c5-c984f3dc6f57.png)
embedding:
![image](https://user-images.githubusercontent.com/26429138/62339839-03d67000-b510-11e9-8759-dbdd25ba115b.png)
start-script-parameter 
![image](https://user-images.githubusercontent.com/26429138/62339860-16e94000-b510-11e9-803a-b9b240e1d615.png)

**Comment by wqh17101** [comment]
选取原始数据的一个part训练是可以得到没问题的结果的
![rBAoL11C3faAQiJwAAAiL0a24zI038](https://user-images.githubusercontent.com/26429138/62344916-a3046300-b522-11e9-9129-4bd06d0b75f5.png)

**Comment by wqh17101** [comment]
正常结果
![image](https://user-images.githubusercontent.com/26429138/62349694-11512180-b533-11e9-968f-32e32fee5161.png)
异常结果
![image](https://user-images.githubusercontent.com/26429138/62349715-1ca44d00-b533-11e9-9da5-8051e28a2b02.png)
![image](https://user-images.githubusercontent.com/26429138/62349728-275ee200-b533-11e9-9001-e56578f83450.png)
看起来似乎出问题的时候loss没有收敛

**Comment by ghandzhipeng** [comment]
Can you please check your input data format?
(We ran into this problem before --- it was caused by the dirty input data)

**Comment by wqh17101** [comment]
the data format is right. I fix it by reducing learning-rate from default(0.1) to 0.01.
So, maybe you can add this example to doc. @ghandzhipeng

**Comment by ghandzhipeng** [comment]
Thanks! Sure, we can do this together.

This bug is weird. Did you dig into why changing learning rate would work?

**Comment by wqh17101** [comment]
学习速率太高调过了局部最优点？
大部分的word2vec的算法中learning-rate都是衰减的，angel没做衰减
Angel 
https://github.com/Angel-ML/angel/blob/092fcb44d27904bd71f3d88ecc6126fea8a39ab6/spark-on-angel/mllib/src/main/scala/com/tencent/angel/spark/ml/embedding/NEModel.scala#L73

![image](https://user-images.githubusercontent.com/26429138/62818424-aed2d380-bb79-11e9-82e9-60d9855766e2.png)
gensim
![image](https://user-images.githubusercontent.com/26429138/62818542-353be500-bb7b-11e9-94bb-e4a58939b6e0.png)

spark.mllib
https://github.com/apache/spark/blob/ef80c3226610cc69e04eaf800e00498c7c23c1fb/mllib/src/main/scala/org/apache/spark/mllib/feature/Word2Vec.scala#L377
![image](https://user-images.githubusercontent.com/26429138/62818445-e5105300-bb79-11e9-9a3a-3cb5ec80b799.png)

**Comment by ghandzhipeng** [comment]
emmm learning rate 不太可能产生NaN, 我这几天查一下。@wqh17101 谢谢！

**Comment by wqh17101** [comment]
没事。
相同参数的情况下，全量数据就会出现这样的问题，选取全量数据的任一partition，就没有任何问题。
然后降低了learning rate 就没问题了。看起来像learning rate 的问题。 @ghandzhipeng
