### ISSUE TITLE
can not find spark-on-angl-env.sh

### ISSUE THREAD

**Issue by zephyr0703** [Angel-ML/angel#851]
I can not find spark-on-angl-env.sh anywhere.
So, how to run spark on angel?

**Comment by paynie** [comment]
In version 3.0, Spark On Angel (sona) has been separated from the angel project and becomes a separate project, placed under https://github.com/Angel-ML. If you are using version 3.0, please refer to the document of the sona project. If you are using the 2.X series, please refer to the documentation for the specific branch.
