### ISSUE TITLE
maven编译出错

### ISSUE THREAD

**Issue by vencent-love-python** [Angel-ML/angel#880]
编译时出现以下错误：

[ERROR] Failed to execute goal com.github.igor-petruk.protobuf:protobuf-maven-plugin:0.6.3:run (d efault) on project angel-ps-core: Protobuf installation version does not match Protobuf library v ersion -> [Help 1]
--

换了几个不同版本的protobuf 还是一样，忒么的干嘛不在master包的依赖加上protobuf-java 的包，还要别人安装，安装又报这样的错

**Comment by krisjin** [comment]
使用 PROTC_HOME=/usr/local/tools/protobuf/protobuf-2.5.0
