### ISSUE TITLE
PS架构下分布式训练是同步的还是异步的呢

### ISSUE THREAD

**Issue by AI-Friend** [Angel-ML/angel#915]
请问PS架构下分布式训练是同步的还是异步的呢？
异步训练对于梯度延迟问题有什么补偿策略吗？
感谢回复！

**Comment by krisjin** [comment]
支持多种同步协议：除了通用的BSP（Bulk Synchronous Parallel）外，为了解决task之间互相等待的问题，Angel还支持SSP（Stale Synchronous Parallel）和ASP（Asynchronous Parallel）

**Comment by krisjin** [comment]
> 请问PS架构下分布式训练是同步的还是异步的呢？
> 异步训练对于梯度延迟问题有什么补偿策略吗？
> 感谢回复！

ConsistencyController 有写

 Angel task consistency controller, Angel support 3 consistency protocol: BSP, SSP, ASYNC. 
If stalenss > 0, means SSP if staleness = 0, means BSP if staleness < 0, means ASYNC



` int staleness = getStaleness(rowIndex.getMatrixId());
    if (staleness >= 0) {
      // For BSP/SSP, get rows from storage/cache first
      int stalenessClock = taskContext.getMatrixClock(rowIndex.getMatrixId()) - staleness;

      findRowsInStorage(taskContext, result, rowIndex, stalenessClock);
      if (!result.isFetchOver()) {
        LOG.debug("need fetch from parameterserver");
        // Get from ps.
        // Wait until the clock value of this row is greater than or equal to the value
        waitForClock(rowIndex.getMatrixId(), -1, stalenessClock);
        PSAgentContext.get().getUserRequestAdapter()
          .getRowsFlow(result, rowIndex, rpcBatchSize, stalenessClock);
      }
      return result;
    } else {
      //For ASYNC, just get rows from pss.
      IntOpenHashSet rowIdSet = rowIndex.getRowIds();
      GetRows func = new GetRows(new GetRowsParam(rowIndex.getMatrixId(), rowIdSet.toIntArray()));
      com.tencent.angel.ml.matrix.psf.get.getrows.GetRowsResult funcResult =
        ((com.tencent.angel.ml.matrix.psf.get.getrows.GetRowsResult) PSAgentContext.get()
          .getUserRequestAdapter().get(func).get());

      if (funcResult.getResponseType() == ResponseType.FAILED) {
        throw new IOException("get rows from ps failed.");
      } else {
        Map<Integer, Vector> rows = funcResult.getRows();
        for (Entry<Integer, Vector> rowEntry : rows.entrySet()) {
          result.put(rowEntry.getValue());
        }
        result.fetchOver();

        return result;
      }`
