### ISSUE TITLE
Java HotSpot(TM) 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)

### ISSUE THREAD

**Issue by maozida880** [Angel-ML/angel#917]
![smv_error](https://user-images.githubusercontent.com/31332809/75633759-bb686780-5c42-11ea-956a-db4a7e89b6ad.png)

---

name: Bug report/Feature request/Question
about: Create a report to help us improve
title: ''
label: bug/enhancement/question
assignees: ''
---

**Environment**:
- Java version:
- Scala version:
- Spark version:
- PyTorch and Python version:
- OS and version:

**Checklist**:
- Did you check if your bug/feature/question is answered in the FQA ?
- Did you search issues to find if somebody discuss your bug/feature/question before?
- If your bug/question is about install, did you read [this doc](../docs/deploy/source_compile_en.md)?
- If your bug/question is about parameter setting, did you read [this doc](../docs/deploy/config_details_en.md)?

**Your Bug/Feature request/Question**: Please describe bug/enhancement/question in detail. 
- For bugs, please post the submit *commands*, *error report logs* and related *code snippet* 
- For feature requests, please describe what's you scenario and why you need this feature. if you required feature is big please connect us email list.

**Comment by graphv** [comment]
请问解决了吗
