### ISSUE TITLE
使用标准数据集在yarn上运行deep and wide报错

### ISSUE THREAD

**Issue by maozida880** [Angel-ML/angel#923]
20/04/09 15:03:47 INFO util.AngelApps: mapreduce.application.classpath=$HADOOP_MAPRED_HOME/*,$HADOOP_MAPRED_HOME/lib/*,$MR2_CLASSPATH
20/04/09 15:03:48 INFO yarn.AngelYarnClient: ApplicationSubmissionContext Queuename :  root.angel
20/04/09 15:03:48 INFO impl.YarnClientImpl: Submitted application application_1584324272021_1511708
20/04/09 15:04:30 INFO yarn.AngelYarnClient: appMaster getTrackingUrl = http://nfjd-hadoop02-node56.jpushoa.com:8088/cluster/app/application_1584324272021_1511708/
20/04/09 15:04:30 INFO yarn.AngelYarnClient: master host=172.16.60.43, port=28179
20/04/09 15:04:30 INFO yarn.AngelYarnClient: start to create rpc client to am
20/04/09 15:04:31 INFO client.AngelClient: clientId=1
20/04/09 15:04:49 INFO yarn.AngelYarnClient: start pss success
20/04/09 15:04:49 INFO client.AngelClient: stop the application
20/04/09 15:04:49 INFO client.AngelClient: master is not null, send stop command to Master, stateCode=0
20/04/09 15:04:49 ERROR utils.AngelRunJar: submit job failed 
java.lang.NullPointerException
	at com.tencent.angel.mlcore.utils.JsonUtils$.layerFromJson(JsonUtils.scala:144)
	at com.tencent.angel.mlcore.utils.JsonUtils$.layerFromJson(JsonUtils.scala:136)
	at com.tencent.angel.ml.core.graphsubmit.AngelModel.buildNetwork(AngelModel.scala:54)
	at com.tencent.angel.ml.core.graphsubmit.GraphRunner.train(GraphRunner.scala:53)
	at com.tencent.angel.ml.core.MLRunner$class.submit(MLRunner.scala:45)
	at com.tencent.angel.ml.core.graphsubmit.GraphRunner.submit(GraphRunner.scala:31)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:91)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:77)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1793)
	at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:77)
	at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:44)

=================================
省略
input_path
model_path
log_path
output_path
daw_json_path

export featureNum=150
export workerNumber=20
export PSNumber=1
export PSMemory=40

hadoop fs -mkdir $model_path
hadoop fs -mkdir $log_path
hadoop fs -mkdir $output_path

/opt/angel/angel-3.0.1-bin/bin/angel-submit \
    -Dangel.job.name=fm_census_deepfm \
    -Daction.type=train \
    -Dangel.app.submit.class=com.tencent.angel.ml.core.graphsubmit.GraphRunner \
    -Dml.model.class.name=com.tencent.angel.ml.core.graphsubmit.AngelModel \
    -Dangel.train.data.path=$input_path \
    -Dangel.save.model.path=$model_path \
    -Dangel.log.path=$log_path \
    -Dangel.workergroup.number=20 \
    -Dangel.worker.memory.gb=20 \
    --angel.worker.task.number 1000 \
    -Dangel.ps.number=$PSNumber \
    -Dangel.ps.memory.gb=$PSMemory \
    -Dangel.output.path.deleteonexist=true \
    --angel.task.data.storage.level memory_disk \
    --angel.task.memorystorage.max.gb 1000 \
    --angel.worker.env "LD_PRELOAD=./libopenblas.so" \
    --angel.ml.conf $daw_json_path \
    -Dml.optimizer.json.provider=com.tencent.angel.ml.core.PSOptimizerProvider \
    --queue root.angel \
    --ml.data.label.trans.class PosNegTrans \
    --ml.data.label.trans.threshold 0.5

======================================
json:
{
  "data": {
    "format": "libsvm",
    "indexrange": 148,
    "numfield": 8,
    "validateratio": 0.1
  },
  "model": {
    "modeltype": "T_DOUBLE_SPARSE_LONGKEY",
    "modelsize": 148
  },
  "train": {
    "epoch": 10,
    "numupdateperepoch": 10,
    "lr": 0.1,
    "decay": 0.8
  },
  "default_optimizer": {
    "type": "momentum",
    "momentum": 0.9,
    "reg2": 0.01
  },
  "layers": [
    {
      "name": "wide",
      "type": "simpleinputlayer",
      "outputdim": 1,
      "transfunc": "identity"
    },
    {
      "name": "embedding",
      "type": "embedding",
      "numfactors": 8,
      "outputdim": 104
    },
    {
     "name": "fclayer",
      "type": "FCLayer",
      "inputlayer": "embedding",
      "outputdims": [
        100,
        100,
        1
      ],
      "transfuncs": [
        "relu",
        "relu",
        "identity"
      ]
    },
    {
      "name": "sumPooling",
      "type": "SumPooling",
      "outputdim": 1,
      "inputlayers": [
        "wide",
        "fclayer"
      ]
    },
    {
      "name": "simplelosslayer",
      "type": "simplelosslayer",
      "lossfunc": "logloss",
      "inputlayer": "sumPooling"
    }
  ]
}

**Comment by maozida880** [comment]
维护Angel是不是不在KPI中啊，这个平台推不动，没有规模优势，有点坑啊

**Comment by PayneJoe** [comment]
> 维护Angel是不是不在KPI中啊，这个平台推不动，没有规模优势，有点坑啊

维护一个大的开源项目成本很大，同时他们也需要更多人的contribution 才能把应用市场打开。好像有个QQ群，可以加进去试试

**Comment by ouyangwen-it** [comment]
> 20/04/09 15:03:47 INFO util.AngelApps: mapreduce.application.classpath=$HADOOP_MAPRED_HOME/_,$HADOOP_MAPRED_HOME/lib/_,$MR2_CLASSPATH
> 20/04/09 15:03:48 INFO yarn.AngelYarnClient: ApplicationSubmissionContext Queuename : root.angel
> 20/04/09 15:03:48 INFO impl.YarnClientImpl: Submitted application application_1584324272021_1511708
> 20/04/09 15:04:30 INFO yarn.AngelYarnClient: appMaster getTrackingUrl = http://nfjd-hadoop02-node56.jpushoa.com:8088/cluster/app/application_1584324272021_1511708/
> 20/04/09 15:04:30 INFO yarn.AngelYarnClient: master host=172.16.60.43, port=28179
> 20/04/09 15:04:30 INFO yarn.AngelYarnClient: start to create rpc client to am
> 20/04/09 15:04:31 INFO client.AngelClient: clientId=1
> 20/04/09 15:04:49 INFO yarn.AngelYarnClient: start pss success
> 20/04/09 15:04:49 INFO client.AngelClient: stop the application
> 20/04/09 15:04:49 INFO client.AngelClient: master is not null, send stop command to Master, stateCode=0
> 20/04/09 15:04:49 ERROR utils.AngelRunJar: submit job failed
> java.lang.NullPointerException
> at com.tencent.angel.mlcore.utils.JsonUtils$.layerFromJson(JsonUtils.scala:144)
> at com.tencent.angel.mlcore.utils.JsonUtils$.layerFromJson(JsonUtils.scala:136)
> at com.tencent.angel.ml.core.graphsubmit.AngelModel.buildNetwork(AngelModel.scala:54)
> at com.tencent.angel.ml.core.graphsubmit.GraphRunner.train(GraphRunner.scala:53)
> at com.tencent.angel.ml.core.MLRunner$class.submit(MLRunner.scala:45)
> at com.tencent.angel.ml.core.graphsubmit.GraphRunner.submit(GraphRunner.scala:31)
> at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:91)
> at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:77)
> at java.security.AccessController.doPrivileged(Native Method)
> at javax.security.auth.Subject.doAs(Subject.java:422)
> at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1793)
> at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:77)
> at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:44)
> 
> =================================
> 省略
> input_path
> model_path
> log_path
> output_path
> daw_json_path
> 
> export featureNum=150
> export workerNumber=20
> export PSNumber=1
> export PSMemory=40
> 
> hadoop fs -mkdir $model_path
> hadoop fs -mkdir $log_path
> hadoop fs -mkdir $output_path
> 
> /opt/angel/angel-3.0.1-bin/bin/angel-submit
> -Dangel.job.name=fm_census_deepfm
> -Daction.type=train
> -Dangel.app.submit.class=com.tencent.angel.ml.core.graphsubmit.GraphRunner
> -Dml.model.class.name=com.tencent.angel.ml.core.graphsubmit.AngelModel
> -Dangel.train.data.path=$input_path
> -Dangel.save.model.path=$model_path
> -Dangel.log.path=$log_path
> -Dangel.workergroup.number=20
> -Dangel.worker.memory.gb=20
> --angel.worker.task.number 1000
> -Dangel.ps.number=$PSNumber
> -Dangel.ps.memory.gb=$PSMemory
> -Dangel.output.path.deleteonexist=true
> --angel.task.data.storage.level memory_disk
> --angel.task.memorystorage.max.gb 1000
> --angel.worker.env "LD_PRELOAD=./libopenblas.so"
> --angel.ml.conf $daw_json_path
> -Dml.optimizer.json.provider=com.tencent.angel.ml.core.PSOptimizerProvider
> --queue root.angel
> --ml.data.label.trans.class PosNegTrans
> --ml.data.label.trans.threshold 0.5
> 
> ======================================
> json:
> {
> "data": {
> "format": "libsvm",
> "indexrange": 148,
> "numfield": 8,
> "validateratio": 0.1
> },
> "model": {
> "modeltype": "T_DOUBLE_SPARSE_LONGKEY",
> "modelsize": 148
> },
> "train": {
> "epoch": 10,
> "numupdateperepoch": 10,
> "lr": 0.1,
> "decay": 0.8
> },
> "default_optimizer": {
> "type": "momentum",
> "momentum": 0.9,
> "reg2": 0.01
> },
> "layers": [
> {
> "name": "wide",
> "type": "simpleinputlayer",
> "outputdim": 1,
> "transfunc": "identity"
> },
> {
> "name": "embedding",
> "type": "embedding",
> "numfactors": 8,
> "outputdim": 104
> },
> {
> "name": "fclayer",
> "type": "FCLayer",
> "inputlayer": "embedding",
> "outputdims": [
> 100,
> 100,
> 1
> ],
> "transfuncs": [
> "relu",
> "relu",
> "identity"
> ]
> },
> {
> "name": "sumPooling",
> "type": "SumPooling",
> "outputdim": 1,
> "inputlayers": [
> "wide",
> "fclayer"
> ]
> },
> {
> "name": "simplelosslayer",
> "type": "simplelosslayer",
> "lossfunc": "logloss",
> "inputlayer": "sumPooling"
> }
> ]
> }

你的数据集是什么样的能说明下吗，数据要和json的一些参数匹配上，embedding layer的ouputdim是embedding dim乘以numfield，看你在文件里设置了numfield为8，embedding dim为8，那么outputdim那应该为64
