### ISSUE TITLE
what kinds of distributed filesystem is supported?

### ISSUE THREAD

**Issue by PayneJoe** [Angel-ML/angel#926]
1. What kinds of distributed filesystems are supported except hdfs?  
2. How can we add the plugins to support other filesystems?

**Comment by krisjin** [comment]
I am in use and currently support HDFS，Other not supported

**Comment by PayneJoe** [comment]
> I am in use and currently support HDFS，Other not supported

Any plans to support cloud APIs? I am really interested

**Comment by krisjin** [comment]
> > I am in use and currently support HDFS，Other not supported
> 
> Any plans to support cloud APIs? I am really interested
I'm doing it myself
