### ISSUE TITLE
English translation of documents

### ISSUE THREAD

**Issue by shunanzhang** [Angel-ML/angel#95]
This is an interesting project. Some friends from other country also want to use it.  An english version of document will be nice for them. I will start translating one by one. Hope more people can join me.

The following order will be expected:

1. Readme.md
2. QuickStart
3. Design
4. Interface
5. Algo

**Comment by andyyehoo** [comment]
Thanks for your nice work. :-)

**Comment by shunanzhang** [comment]
Thanks for the revision

**Comment by shunanzhang** [comment]
mf_on_angel_en.md was merged into 1.0.0, but not included in master branch. Could you double check?
