### ISSUE TITLE
求助:目前和yarn 3.0.0好像不兼容.

### ISSUE THREAD

**Issue by boylige** [Angel-ML/angel#971]

**Comment by ouyangwen-it** [comment]
hadoop2和hadoop3的代码很多接口都是不兼容的，所以我们提供的支持hadoop3的分支，如果要使用hadoop3的话请使用带hadoop3的分支。

**Comment by boylige** [comment]
> hadoop2和hadoop3的代码很多接口都是不兼容的，所以我们提供的支持hadoop3的分支，如果要使用hadoop3的话请使用带hadoop3的分支。

 怎么看出是带hadoop3的分支
