### ISSUE TITLE
研究了挺长时间Angel，但从来没有成功在集群上跑起来，各种各样的错误，五花八门。没有文档，没有答疑，没有资料，说实话国内的开源水平也就这样了。

### ISSUE THREAD

**Issue by boylige** [Angel-ML/angel#992]

**Comment by boylige** [comment]
说实话，于其搞这么多功能，不如先把易用性和稳定性提升上去，不然再好也没有人使用。

**Comment by Ethan199111** [comment]
国内水平就这样，有就不错了，至少你还能学习下parameter server的原理

**Comment by Phoenixinfire** [comment]
我倒是跑起来过，但是遇到了太多问题了，后来放弃了，是不是内部也放弃了。都这么多年了官方文档都不弄一个，咋想的

**Comment by ouyangwen-it** [comment]
运行文档官方主页都有提供的，https://github.com/Angel-ML/angel/tree/branch-3.1.0，能详细描述下您遇到的问题吗
